[terminal]
[terminal.shell]
program = "zellij"
args = ["-l", "welcome"]

[window]
opacity=0.95
blur=true

[window.dimensions]
columns=180
lines=50

[font]
size=11.5
[font.normal]
family="Cascadia Code NF"
style="Light"
